<a href="https://colab.research.google.com/github/Nanthakan670510759/229352-Labs/blob/main/Lab08_Pytorch_670510759_Nanthakan_rotdi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [1]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a=torch.tensor(2)
a

tensor(2)

In [ ]:
b=torch.tensor(6)
a*b

tensor(12)

In [ ]:
a = torch.tensor(8)
b = torch.tensor(9)
print(a)
print(b)
print(a+b)

### Convert a tensor to scalar

In [ ]:
c=b.item()
c

6

In [ ]:
a.item()

### Creating 2D tensor

In [ ]:
A = torch.tensor([[1, 2], [3, 4]])
print(A)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
B=A.numpy()
B

array([[1, 2],
       [3, 4]])

In [ ]:
A.numpy()

### Convert from numpy array to tensor

In [ ]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [3, 4]])

check GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
C.device

device(type='cpu')

In [ ]:
D=C.cuda()
D

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [ ]:
D.device
D

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [ ]:
C+D#

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
# D.numpy()
E=D.cpu().numpy()
E

array([[1, 2],
       [3, 4]])

## Basic operations

In [ ]:
E-2

array([[-1,  0],
       [ 1,  2]])

In [ ]:
D = 2*C

E = C - 10

print(D)
print(E)

tensor([[2, 4],
        [6, 8]])
tensor([[-9, -8],
        [-7, -6]])


### Matrix multiplication

In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[5,6],[7,8]])
torch.matmul(A,B)

tensor([[19, 22],
        [43, 50]])

In [ ]:
torch.mm(A,B)

tensor([[19, 22],
        [43, 50]])

In [ ]:
A@B

tensor([[19, 22],
        [43, 50]])

In [ ]:
print(torch.matmul(D, E))
print(torch.mm(D, E))
print(D @ E)

tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])
tensor([[ -46,  -40],
        [-110,  -96]])


### Matrix transpose

In [ ]:
A@B.t()

tensor([[17, 23],
        [39, 53]])

In [ ]:
print(C)
print( C.t() )

## Creating a specific type of tensor

In [ ]:
a=torch.zeros(1,2,3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
b=torch.ones(1,2,3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
i=torch.eye(3)
i

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
r1=torch.rand(2,3)
r1

tensor([[0.9479, 0.8484, 0.1558],
        [0.7433, 0.0311, 0.0814]])

In [ ]:
r2=torch.randn(2,3)
r2

tensor([[ 0.5271,  0.6003, -1.2006],
        [ 0.5693, -1.8674, -0.3794]])

In [ ]:
# print(torch.zeros(2,3))
# print(torch.ones(2,3))
# print(torch.rand(2,3))
# print(torch.randn(2,3))  # sample each number from N(0, 1)
# print(torch.arange(9))

## Tensor's shape

### Checking the shape of a tensor

In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
A.size()

torch.Size([2, 2])

In [ ]:
F = torch.zeros((4, 5))
print(F.shape)
print(F.size())

### Changing the shape of a tensor

In [ ]:
u=torch.arange(6)
u.shape

torch.Size([6])

In [ ]:
v=u.reshape(2,3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
G = torch.arange(6)
print(G.view(2, 3))
print(G.reshape(2, 3))

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a=torch.arange(4)
b=torch.arange(4)+1
c=torch.stack([a,b],axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [ ]:
d=torch.stack([a,b],axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
e=torch.cat([a,b],axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [ ]:
H = torch.arange(6)
I = torch.stack([H, H, H, H], axis=0)
J = torch.stack([H, H, H, H], axis=1)
print(I)
print(J)

In [ ]:
# concatenate

I = torch.cat([H, H, H, H], axis=0)
print(I)
# J = torch.cat([H, H, H, H], axis=1)
#print(J)

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A=torch.zeros(1,2,3)
m=A.squeeze()
m.shape

torch.Size([2, 3])

In [ ]:
n=B.unsqueeze(axis=0)
n.shape

torch.Size([1, 2, 2])

In [ ]:
# [[1,2]] this is (1,2) tensor, want (2,)
print("H=", H) # shape = (6,)
K = H.reshape(1,6)
print("K=", K)
print(K.shape)

In [ ]:
print(K.squeeze())

In [ ]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

## PyTorch and GPU

check if GPU is available

In [16]:
torch.cuda.is_available()

True

In [ ]:
Q = torch.tensor([1, 2, 3])
print(Q.device)

In [ ]:
R = Q.to('cuda')
print(Q.device)
print(R.device)

In [ ]:
R.cpu().numpy()

In [ ]:
torch.inverse(torch.tensor([[2.0,0.0],[2.2,2.5]]))

tensor([[ 0.5000,  0.0000],
        [-0.4400,  0.4000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [2]:
X=torch.randn(200,7)
b=torch.ones(8,1)
e=torch.randn(200,1)
X.shape,b.shape,e.shape

(torch.Size([200, 7]), torch.Size([8, 1]), torch.Size([200, 1]))

In [9]:
one=torch.ones(200,1)
one

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [4]:
X=torch.cat([one,X],axis=1)
X.shape

torch.Size([200, 8])

In [5]:
y=X@b+e
y

tensor([[ 1.2356e+00],
        [ 3.9835e+00],
        [ 2.6993e+00],
        [-3.9575e+00],
        [-1.4274e+00],
        [ 4.4149e-01],
        [ 3.4177e+00],
        [ 5.5213e-01],
        [ 3.3148e-01],
        [-2.0232e+00],
        [-4.4882e-01],
        [ 2.6169e-01],
        [-2.6876e-01],
        [ 5.4027e+00],
        [ 5.6266e+00],
        [-1.0431e+00],
        [ 3.5172e-01],
        [-3.6615e-01],
        [ 1.1972e+00],
        [-2.9019e+00],
        [ 4.2098e+00],
        [-3.6113e+00],
        [ 4.3875e+00],
        [ 3.2756e+00],
        [-3.5095e+00],
        [ 4.6495e+00],
        [-2.1575e+00],
        [ 1.1928e+00],
        [-3.1312e-01],
        [ 3.3902e+00],
        [-5.8025e-01],
        [ 3.6893e-01],
        [ 1.3381e+00],
        [ 1.4753e+00],
        [-1.1117e+00],
        [-1.2064e+00],
        [ 1.8662e+00],
        [ 1.5342e+00],
        [ 3.5853e+00],
        [-1.8107e+00],
        [-2.1224e+00],
        [-4.8043e-02],
        [ 9.7253e-01],
        [ 5

In [6]:
b_hat=torch.inverse(X.T@X)@X.T@y
b_hat

tensor([[0.9048],
        [1.1035],
        [0.9130],
        [1.1309],
        [0.9710],
        [0.8404],
        [0.9737],
        [1.0425]])

In [7]:
y_hat=X@b_hat
y_hat

tensor([[ 1.2926e+00],
        [ 4.5159e+00],
        [ 2.8420e+00],
        [-1.8255e+00],
        [-2.6469e+00],
        [ 1.1073e+00],
        [ 3.8012e+00],
        [ 3.1760e-01],
        [ 2.2251e+00],
        [-2.7770e+00],
        [-7.5378e-01],
        [ 1.1241e+00],
        [-5.4074e-01],
        [ 5.1540e+00],
        [ 5.1476e+00],
        [-4.9935e-01],
        [ 7.6109e-01],
        [ 1.7770e+00],
        [ 1.6461e-01],
        [-2.2327e+00],
        [ 3.7316e+00],
        [-2.3558e+00],
        [ 5.3741e+00],
        [ 2.6798e+00],
        [-3.3547e+00],
        [ 4.0925e+00],
        [-2.4061e+00],
        [ 4.3251e-01],
        [-2.3551e-01],
        [ 3.6271e+00],
        [-1.8610e-01],
        [ 1.4935e+00],
        [ 1.9529e+00],
        [ 1.6448e+00],
        [-2.8256e-01],
        [-1.3810e+00],
        [ 2.6581e+00],
        [ 5.9272e-01],
        [ 1.8914e+00],
        [-2.2265e+00],
        [-7.2032e-01],
        [ 1.2240e+00],
        [ 8.3373e-01],
        [ 1

In [8]:
y=y.numpy()
y_hat=y_hat.numpy()

mse=np.mean((y-y_hat)**2)
print(mse)

1.0289636


In [ ]:
# X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
# print(X)

# X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
# print(X)